function dx = trig_dyn_t_plan_to_t_total(in1,udummy)
%TRIG_DYN_T_PLAN_TO_T_TOTAL
%    DX = TRIG_DYN_T_PLAN_TO_T_TOTAL(IN1,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    05-Jun-2022 22:28:47

cqi = in1(1,:);
dqi = in1(3,:);
kai = in1(4,:);
kvi = in1(5,:);
sqi = in1(2,:);
dx = [-dqi.*sqi;cqi.*dqi;-kai-kvi.*2.0;0.0;0.0;1.0];
